IMS/urls.py
from django.urls import path
from . views import *

urlpatterns = [
    # 1. String: Browser url :path, 2. String: Views.py def name, 3: String: Html template link name using dynamic url

    path('', home, name='home'),
    path('inventory', inventory, name='inventory'),
    path('additem', additem, name='additem'),
    path('sellitem/<int:Id>/', sellitem, name='sellitem'),
    path('edititem/<int:Id>/', edititem, name='edititem'),
    path('viewitem/<int:Id>/', viewitem, name='viewitem'),
    path('orderlist', orderlist,  name='orderlist'),
    path('orderitem/<int:Id>/', orderitem, name='orderitem'),
    path('order_placed', order_placed, name='order_placed'),
    path('orderstatus', orderstatus, name='orderstatus'),
    path('order_received', order_received, name='order_received'),
    path('order_canceled', order_canceled, name='order_canceled'),
    path('transactionlist', transactionlist, name='transactionlist'),
    path('itemsold', itemsold, name='itemsold'),
    path('management', management, name='management'),
]

app_name = 'IMS'

sopeo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('IMS.urls')), # Registering the application urls

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

IMS/models.py
from django.db import models

# Create your models here.
class Inventory(models.Model):
    Id =  models.AutoField(primary_key=True)
    Name = models.CharField(max_length=50, null=True, blank=True)
    IIN = models.CharField(max_length=10, null=True, blank=True)
    Cost = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=10)
    Quantity = models.PositiveIntegerField(null=True, blank=True, default=0)
    Quantity_sold = models.PositiveIntegerField(null=True, blank=True, default=0)
    Selling_price = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=10)
    Item_profit = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=10)
    Profit_earned = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=10, default=0)
    Revenue = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=10, default=0)
    
class Order(models.Model):
    Id =  models.AutoField(primary_key=True)
    Name = models.CharField(max_length=50, null=True, blank=True)
    Item = models.ForeignKey(Inventory, on_delete=models.CASCADE, null=True)
    Quantity = models.PositiveIntegerField(null=True, blank=True)
    Cost = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=10)
    Orderdttm = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    Is_received = models.BooleanField(default=False)
    Is_cancel = models.BooleanField(default=False)

class Transaction(models.Model):
    Id =  models.AutoField(primary_key=True)
    Name = models.CharField(max_length=50, null=True, blank=True)
    Item = models.ForeignKey(Inventory, on_delete=models.CASCADE, null=True)
    Quantity = models.PositiveIntegerField(null=True, blank=True)
    Selling_price = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=10)
    Transactiondttm = models.DateTimeField(null=True, blank=True, auto_now_add=True)

IMS/forms.py
from typing import Any
from django import forms
from .models import Inventory, Order, Transaction

class AddItemForm(forms.ModelForm):
    Name = forms.CharField(required=True)
    Cost = forms.DecimalField(required=True)
    Selling_price = forms.DecimalField(required=True)
    class Meta:
        model = Inventory
        fields = [
            "Name",
            "Cost",
            "Selling_price",
        ]

class EditItemForm(forms.ModelForm):
    Name = forms.CharField(required=True)
    Cost = forms.DecimalField(required=True)
    Selling_price = forms.DecimalField(required=True)
    class Meta:
        model = Inventory
        fields = [
            "Name",
            "Cost",
            "Selling_price",
        ]


class OrderItemForm(forms.ModelForm):
    Name = forms.CharField(required=True, widget=forms.TextInput(attrs={'readonly':'readonly'}))
    Quantity = forms.DecimalField(required=True, min_value=1)
    Cost = forms.DecimalField(required=True)
    class Meta:
        model = Order
        fields = [
            "Name",
            "Quantity",
            "Cost",
            "Item",
        ]

class SellItemForm(forms.ModelForm):
    Name = forms.CharField(required=True)
    Stock = forms.DecimalField(required=True, widget=forms.TextInput(attrs={'readonly':'readonly'}))
    Quantity = forms.DecimalField(required=True, min_value=1)
    Selling_price = forms.DecimalField(required=True)
    class Meta:
        model = Transaction
        fields = [
            "Name",
            "Quantity",
            "Selling_price",
            "Item",
        ]

IMS/views.py
from django.shortcuts import render
from django.shortcuts import redirect
#from django.http import HttpResponse
from .models import Inventory, Order, Transaction
from .forms import AddItemForm , SellItemForm , EditItemForm, OrderItemForm
from django.conf import settings
import json

managementjson = settings.MEDIA_ROOT / 'management.json'

# Create your views here.

def management(request):
    try:
        with open(managementjson) as f:
            data = json.load(f)
    except: data = {}

    jsonData = json.dumps(data)
    context = {'jsonData' : jsonData, 'data' : data}
    context.update(data)
    return render(request, 'IMS/management.html', context)


def home(request):
    list1 = sum(Inventory.objects.values_list('Profit_earned', flat=True))
    list2 = sum(Inventory.objects.values_list('Quantity', flat=True))
    list3 = Inventory.objects.order_by('-Selling_price').first()
    list4 = Inventory.objects.order_by('-Quantity_sold').first()
    list5 = Inventory.objects.order_by('-Profit_earned').first()
    list6 = Inventory.objects.filter(Quantity=0).values()
    list7 = Inventory.objects.order_by('-Item_profit').first()
    context = {'list1' : list1, 'list2' : list2, 'list3' : list3, 'list4' : list4, 'list6' : list6, 'list5' : list5, 'list7' : list7}
    return render(request, 'IMS/home.html', context)

def inventory(request):
    list = Inventory.objects.all()
    list = list.values()
    context = {'list' : list, 'title' : "Inventory Management System"}
    return render(request, 'IMS/inventory.html', context=context)
    

def additem(request):
    if request.method == 'POST':
        form = AddItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/inventory')
    form = AddItemForm()
    context = {'form':form,'form_title':"Add Item", 'form_action':"Add Item to Inventory"}
    return render(request, 'IMS/additem.html', context=context)


def edititem(request, Id):
    list_item = Inventory.objects.get(Id=Id)
    if request.method == 'POST':
        form = EditItemForm(request.POST, instance=list_item)
        if form.is_valid():
            form.save()
            return redirect('/inventory')
    else:
        form = EditItemForm(instance=list_item)
    context = {'form': form, 'form_title':"Edit Item", 'form_action':"Edit"}
    return render(request, 'IMS/additem.html', context)


def viewitem(request,Id):
    list_item = Inventory.objects.filter(Id=Id).values()
    context = {'Id':Id,'list_item':list_item}
    return render(request, 'IMS/viewitem.html', context=context)

def orderitem(request,Id):
    list_item = Inventory.objects.get(Id=Id)
    initial_data = {
        "Name" : list_item.Name,
        "Quantity" : 1,
        "Cost" : list_item.Selling_price,
        "Item" : list_item.Id
    }
    if request.method == 'POST':
        form = OrderItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/order_placed?Id='+str(Id))
    else:
        form = OrderItemForm(instance=list_item, initial=initial_data)
    context = {'form': form, 'list_item':list_item}
    return render(request, 'IMS/orderitem.html', context)

def orderlist(request):
    list = Order.objects.all()
    list = list.values()
    context = {'list' : list}
    return render(request, 'IMS/orderlist.html', context)

def order_placed(request):
    Id = request.GET.get('Id', None)
    list = Order.objects.filter(Item_id=Id).values().filter(Is_received = False).filter(Is_cancel = False)
    context = {'list' : list}
    return render(request, 'IMS/order_placed.html', context)

def orderstatus(request):
    status = request.GET.get('status', None)
    orderid = request.GET.get('orderid', None)
    itemid = request.GET.get('itemid', None)
    if status is not None:
        order = Order.objects.get(Id=orderid)
        print(order,"hi")
        if status == "receive":
            order.Is_received = True
            list_item = Inventory.objects.get(Id=itemid)
            quantity = order.Quantity
            list_item.Quantity = quantity + list_item.Quantity
            list_item.save()
        else:
            order.Is_cancel = True
        order.save()
    list = Order.objects.all()
    list = list.values()
    context = {'list' : list}
    return render(request, 'IMS/orderlist.html', context)

def order_received(request):
    Id = request.GET.get('Id', None)
    list = Order.objects.filter(Item_id=Id).values().filter(Is_received = True)
    context = {'list' : list}
    return render(request, 'IMS/order_received.html', context)

def order_canceled(request):
    Id = request.GET.get('Id', None)
    list = Order.objects.filter(Item_id=Id).values().filter(Is_cancel = True)
    context = {'list' : list}
    return render(request, 'IMS/order_canceled.html', context)

def transactionlist(request):
    list = Transaction.objects.all()
    list = list.values()
    context = {'list' : list}
    return render(request, 'IMS/transactionlist.html', context)

def sellitem(request,Id):
    list_item = Inventory.objects.get(Id=Id)
    initial_data = {
        "Name" : list_item.Name,
        "Quantity" : 1,
        "Stock" : list_item.Quantity,
        "Selling_price" : list_item.Selling_price,
        "Item" : list_item.Id
    }
    if request.method == 'POST':
        form = SellItemForm(request.POST)
        if form.is_valid():
            form.save()
            quantity_sold = form.cleaned_data['Quantity']
            list_item.Quantity_sold = list_item.Quantity_sold + quantity_sold
            list_item.Quantity = list_item.Quantity - quantity_sold
            list_item.Item_profit = list_item.Selling_price - list_item.Cost
            list_item.Profit_earned = list_item.Quantity_sold * list_item.Item_profit
            list_item.Revenue = list_item.Quantity_sold * list_item.Cost
            list_item.save()
            return redirect('/transactionlist')
    form = SellItemForm(initial=initial_data)
    context = {'form':form, 'Id':Id, 'list_item' : list_item}
    return render(request, 'IMS/sellitem.html', context=context)

def itemsold(request):
    Id = request.GET.get('Id', None)
    list = Transaction.objects.filter(Item_id=Id).values()
    context = {'list' : list}
    return render(request, 'IMS/itemsold.html', context)










       

IMS/templates/IMS/additem.html
{% extends 'IMS/base.html' %}
{% load static %}
{% block content %}

<h1>{{form_title}}</h1>
<div>
    <form method="post" id="add_form">
        {% csrf_token %}
        {{ form.as_p }}
        <input id="id_additem" class="btn btn-primary" type="submit" value="{{form_action}}">
        <p id="message1"></p>
        <p id="message2"></p>
    </form>
</div>

<script>
    let add_btn = document.getElementById("id_additem");
    add_btn.addEventListener("click",(event) => {
        event.preventDefault();
        let sp = document.getElementById("id_Selling_price").value;
        let cp = document.getElementById("id_Cost").value;
        let message1 = document.getElementById("message1");
        let message2 = document.getElementById("message2");
        if(sp < cp){
            message1.innerText = "Selling price must be greater than Cost";
            return false;
        }
        else if( (sp - cp)> cp){
            message2.innerText = "Profit can't be more than Cost price";
            return false;
        }
        else{
            let add_form = document.getElementById("add_form");
            add_form.submit();
        }
    })
</script>
{% endblock %}

IMS/templates/IMS/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{title}}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" >
</head>
<header>
    <nav class="ims_nav">
        <p class="title">Inventory Management System</p>
        <ul>
            <li><a class="link-offset-2 link-underline link-underline-opacity-0" href="{% url 'IMS:home' %}">Home</a></li>
            <li><a class="link-offset-2 link-underline link-underline-opacity-0"  href="{% url 'IMS:inventory' %}">Inventory</a></li>
            <li><a class="link-offset-2 link-underline link-underline-opacity-0"href="{% url 'IMS:orderlist' %}">Orders</a></li>
            <li><a class="link-offset-2 link-underline link-underline-opacity-0"href="{% url 'IMS:transactionlist' %}">Transactions</a></li>
            <li><a class="link-offset-2 link-underline link-underline-opacity-0"href="{% url 'IMS:management' %}">Management Live</a></li>
        </ul>
    </nav>
</header>
<body>     
    {% block content %}
    
    {% endblock %}    
</body>
</html>

IMS/templates/IMS/home.html
{% extends 'IMS/base.html' %}
{% load static %}
{% block content %}
    <h1>Dashboard</h1>
    <section class="home-page">
        <div class="top-cards">
            <div class="card text-white bg-success mb-3">
                <h2 class="card-header">Total Store Profit</h2>
                <p class="card-text">Rs.{{list1}}</p>
            </div>
            <div class="card text-white bg-warning mb-3">
                <h2 class="card-header">Total Items in Stock</h2>
                <p class="card-text">{{list2}}</p>
            </div>
        </div>
        <div class="middle-cards">
            <div class="card bg-light mb-3">
                <h2 class="card-header">Item with Highest Cost</h2>
                <table class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Name</th>
                        <th scope="col">Stock</th>
                        <th scope="col">Selling_price</th>
                      </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{list3.Id}}</td>
                            <td>{{list3.Name}}</td>
                            <td>{{list3.Quantity}}</td>
                            <td>{{list3.Selling_price}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="card text-white bg-secondary mb-3">
                <h2 class="card-header">Item with Highest Profits</h2>
                <table class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Name</th>
                        <th scope="col">Stock</th>
                        <th scope="col">Selling_price</th>
                      </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{list7.Id}}</td>
                            <td>{{list7.Name}}</td>
                            <td>{{list7.Quantity}}</td>
                            <td>{{list7.Selling_price}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="card bg-light mb-3">
                <h2 class="card-header">Item Most Sold</h2>
                <table class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Name</th>
                        <th scope="col">Stock</th>
                        <th scope="col">Selling_price</th>
                      </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{list4.Id}}</td>
                            <td>{{list4.Name}}</td>
                            <td>{{list4.Quantity}}</td>
                            <td>{{list4.Selling_price}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="end-cards">
            <div class="card text-white bg-secondary mb-3">
                <h2 class="card-header">Items Out of Stock</h2>
                <table class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Name</th>
                        <th scope="col">Stock</th>
                        <th scope="col">Selling_price</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for i in list6 %}
                            <tr>
                                <td>{{i.Id}}</td>
                                <td>{{i.Name}}</td>
                                <td>{{i.Quantity}}</td>
                                <td>{{i.Selling_price}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card bg-light mb-3">
                <h2 class="card-header">Item with Highest Profit Earned</h2>
                <table class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Name</th>
                        <th scope="col">Stock</th>
                        <th scope="col">Selling_price</th>
                      </tr>
                    </thead>
                    <tbody>
                            <tr>
                                <td>{{list5.Id}}</td>
                                <td>{{list5.Name}}</td>
                                <td>{{list5.Quantity}}</td>
                                <td>{{list5.Selling_price}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        
    </section>
{% endblock %}
    

IMS/templates/IMS/inventory.html
{% extends 'IMS/base.html' %}
{% load static %}
{% block content %}
<main>
    <h1>Inventory Item List</h1>
    <a class="btn btn-primary" href="{% url 'IMS:additem' %}" role="button">Add item to Inventory</a>
    <p></p>
    <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">IIN</th>
            <th scope="col">Cost</th>
            <th scope="col">Quantity</th>
            <th scope="col">Quantity_sold</th>
            <th scope="col">Selling_price</th>
            <th scope="col">Item_profit</th>
            <th scope="col">Profit_earned</th>
            <th scope="col">Revenue</th>
            <th scope="col">View</th>
            <th scope="col">Edit</th>
            <th scope="col">Sell</th>
            <th scope="col">Order</th>
          </tr>
        </thead>
        <tbody>
            {% for i in list %}
            <tr>
                <td>{{i.Id}}</td>
                <td>{{i.Name}}</td>
                <td>item{{i.Id}}</td>
                <td>{{i.Cost}}</td>
                <td>{{i.Quantity}}</td>
                <td>{{i.Quantity_sold}}</td>
                <td>{{i.Selling_price}}</td>
                <td>{{i.Item_profit}}</td>
                <td>{{i.Profit_earned}}</td>
                <td>{{i.Revenue}}</td>
                <td><a class="btn btn-primary" href="{% url 'IMS:viewitem' i.Id %}" role="button">Veiw</a></td>
                <td><a class="btn btn-primary" href="{% url 'IMS:edititem' i.Id %}" role="button">Edit</a></td>
                <td><a class="btn btn-primary" href="{% url 'IMS:sellitem' i.Id %}" role="button">Sell</a></td>
                <td><a class="btn btn-primary" href="{% url 'IMS:orderitem' i.Id %}" role="button">Order</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</main>

    {% endblock %}

    

IMS/templates/IMS/itemsold.html
{% extends 'IMS/base.html' %}
{% load static %}
{% block content %}
<main>
  <h1>Item Transactions</h1>
  <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Name</th>
          <th scope="col">Item</th>
          <th scope="col">Quantity</th>
          <th scope="col">Selling_price</th>
          <th scope="col">Transactiondttm</th>
        </tr>
      </thead>
      <tbody>
          {% for i in list %}
          <tr>
              <td>{{i.Id}}</td>
              <td>{{i.Name}}</td>
              <td>{{i.Item_id}}</td>
              <td>{{i.Quantity}}</td>
              <td>{{i.Selling_price}}</td>
              <td>{{i.Transactiondttm}}</td>
          </tr>
          {% endfor %}
      </tbody>
  </table>
</main>
{% endblock %}

IMS/templates/IMS/order_canceled.html
{% extends 'IMS/base.html' %}
{% load static %}
{% block content %}
<main>
  <h1>Order Cancel List</h1>
  <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Name</th>
          <th scope="col">Item_id</th>
          <th scope="col">Quantity</th>
          <th scope="col">Cost</th>
          <th scope="col">Orderdttm</th>
          <th scope="col">Is_receive</th>
          <th scope="col">Is_cancel</th>
        </tr>
      </thead>
      <tbody>
          {% for i in list %}
          <tr>
              <td>{{i.Id}}</td>
              <td>{{i.Name}}</td>
              <td>{{i.Item_id}}</td>
              <td>{{i.Quantity}}</td>
              <td>{{i.Cost}}</td>
              <td>{{i.Orderdttm}}</td>
              <td>{{i.Is_received}}</td>
              <td>{{i.Is_cancel}}</td>
          </tr>
          {% endfor %}
      </tbody>
  </table>
</main>

{% endblock %}

IMS/templates/IMS/order_placed.html
{% extends 'IMS/base.html' %}
{% load static %}
{% block content %}
<main>
  <h1>Order Placed List</h1>
<table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
        <th scope="col">Item_id</th>
        <th scope="col">Quantity</th>
        <th scope="col">Cost</th>
        <th scope="col">Orderdttm</th>
        <th scope="col">Receive</th>
        <th scope="col">Cancel</th>
      </tr>
    </thead>
    <tbody>
        {% for i in list %}
        <tr>
            <td>{{i.Id}}</td>
            <td>{{i.Name}}</td>
            <td>{{i.Item_id}}</td>
            <td>{{i.Quantity}}</td>
            <td>{{i.Cost}}</td>
            <td>{{i.Orderdttm}}</td>
            <td><a class="btn btn-primary" href="{% url 'IMS:orderstatus' %}?orderid={{i.Id}}&itemid={{i.Item_id}}&status=receive" role="button">Receive</a></td>
            <td><a class="btn btn-primary" href="{% url 'IMS:orderstatus' %}?orderid={{i.Id}}&itemid={{i.Item_id}}&status=cancel" role="button">Cancel</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</main>

{% endblock %}

IMS/templates/IMS/order_received.html
{% extends 'IMS/base.html' %}
{% load static %}
{% block content %}
<main>
  <h1>Order Received List</h1>
<table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
        <th scope="col">Item_id</th>
        <th scope="col">Quantity</th>
        <th scope="col">Cost</th>
        <th scope="col">Orderdttm</th>
        <th scope="col">Is_receive</th>
        <th scope="col">Is_cancel</th>
      </tr>
    </thead>
    <tbody>
        {% for i in list %}
        <tr>
            <td>{{i.Id}}</td>
            <td>{{i.Name}}</td>
            <td>{{i.Item_id}}</td>
            <td>{{i.Quantity}}</td>
            <td>{{i.Cost}}</td>
            <td>{{i.Orderdttm}}</td>
            <td>{{i.Is_received}}</td>
            <td>{{i.Is_cancel}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</main>

{% endblock %}

IMS/templates/IMS/orderitem.html
{% extends 'IMS/base.html' %}
{% load static %}
{% block content %}
<h1>Order Item</h1>
<div>
    <form method="post" id="order_form">
        {% csrf_token %}
        {{ form.as_p }}
        <div id="id_item_price" data-sp="{{list_item.Selling_price}}"></div>
        <input id="id_orderitem" class="btn btn-primary" type="submit" value="Order">
        <p id="message"></p>
    </form>
</div>

    
<script>
    let quantity = document.getElementById("id_Quantity");
    let cost = document.getElementById("id_Cost");
    let item_price = parseFloat(document.getElementById("id_item_price").getAttribute("data-sp"));
    cost.readOnly = true;
    quantity.addEventListener("input",(event) => {
        event.preventDefault();
        if(quantity.value>1){
            cost.value = quantity.value*item_price;
        }
        else if(quantity.value==1){
            cost.value = item_price;
        }
    })
</script>

{% endblock %}

IMS/templates/IMS/viewitem.html
{% extends 'IMS/base.html' %}
{% load static %}
{% block content %}
<main>
  <h1>Item Details</h1>
<table class="table table-bordered table-striped table-sm">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">IIN</th>
      <th scope="col">Cost</th>
      <th scope="col">Quantity</th>
      <th scope="col">Quantity_sold</th>
      <th scope="col">Selling_price</th>
      <th scope="col">Profit_earned</th>
      <th scope="col">Revenue</th>    
    </tr>
  </thead>
  <tbody>
      <tr>
          {% for item in list_item %}
            <td>{{item.Id}}</td>
            <td>{{item.Name}}</td>
            <td>item{{item.Id}}</td>
            <td>{{item.Cost}}</td>
            <td>{{item.Quantity}}</td>
            <td>{{item.Quantity_sold}}</td>
            <td>{{item.Selling_price}}</td>
            <td>{{item.Profit_earned}}</td>
            <td>{{item.Revenue}}</td>
          {% endfor %}
      </tr>
  </tbody>
</table>
{% for item in list_item %}
<a class="btn btn-primary" href="{% url 'IMS:edititem' item.Id %}" role="button">Edit</a>
<a class="btn btn-primary" href="{% url 'IMS:orderitem' item.Id %}" role="button">Order</a>
<a class="btn btn-primary" href="{% url 'IMS:order_placed' %}?Id={{item.Id}}" role="button">Order Placed</a>
<a class="btn btn-primary" href="{% url 'IMS:order_received' %}?Id={{item.Id}}" role="button">Order Received</a>
<a class="btn btn-primary" href="{% url 'IMS:order_canceled' %}?Id={{item.Id}}" role="button">Order Canceled</a>
<a class="btn btn-primary" href="{% url 'IMS:itemsold' %}?Id={{item.Id}}" role="button">Transactions</a>
{% endfor %}
</main>




{% endblock %}